### PR TITLE
google calendar fix

### PR DESCRIPTION
**Pull request by Gioelio**
# sabesansathananthan.github.io

GitHub Flow PR Image

Thank you so much for opening a pull request! :smiley:

Please provide the following information where possible to help the pull request reviewer merge your PR quicker!

## Relevant Project Issue Numbers :hash:

*Add any related issue numbers from the GitHub project. Append the `#` symbol before issue numbers.*

>e.g. #58

## Involved Project Members :bust_in_silhouette:

*Tag any GitHub usernames involved or directly responsible for reviewing the proposed changes. Append the `@` symbol before usernames.*

>e.g @Charlotteis
 
## An Explanation of Your Changes :speech_balloon:

I've take google code and modify it with php script, you can modify it if you want to customize
 your google calendar

## Any Screenshots of Your Changes :camera:
 
*Your screenshots go here! Use Markdown Syntax to embed images.*

### CODE REVIEW

**Comment by sabesansathananthan** [comment]
Nice work :clap: 

I suggest you to participate https://hacktoberfest.digitalocean.com/details#quality-standards

**Comment by Gioelio** [comment]
Yes, i’ve already on

**Comment by sabesansathananthan** [comment]
Please run the file when I click google clander. php is downloading. please fix it and clander was not there.

Screenshot from 2019-10-25 16-00-54

**Comment by Gioelio** [comment]
Because my code delete all and write only the event that are in your google
calendar, try to add one and tell me what you see. Anyway in the code when
you call google_calendar.php if you add”?v=...” month/year you can change
your output

**Pull request merged**
